# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name| "https://github.com/#{repo_name}" end

# gem "rails"
group :development, :test do
  gem 'byebug'
  gem 'rspec'
end
